### ISSUE TITLE
License Choices Discussion

### ISSUE THREAD

**Issue by fei-chang** [UBC-MDS/ploteasyr#17]
License choice
- For python: MIT
- For R: currently no license is specified for R

MIT License is a license that permits commercial use, modification, distribution and private use. I feel a little concerned with the permission to commercial use. I think that the codes we developed are only for private use or educational purpose and therefore shouldn't be used for commercial profits.

 Maybe we can look for some licenses which have stricter permission requirements.

**Comment by zhijingjing1** [comment]
Yes, I agree. From my perspective, MIT License is good since it's permissive.  But I think because our function are sample and easy to be modified, I hope that changes in our package can be documented. I would recommend GNU License.

**Comment by fei-chang** [comment]
I would say GNU is more reasonable to me.  It seems that any derivative work must be distributed under the same or equivalent license terms.

**Comment by Julie-M-Zhu** [comment]
I think we can use Boost Software License. The content is very similar to MIT License. But Boost Software License enumerates the things a user is permitted to do.

**Comment by fei-chang** [comment]
I would vote for GNU compared to Boost Software License. As I searched I found the terms of Boost Software License very confusing. GNU is more widely used and has clearer explanations in terms. So I would vote for GNU.

**Comment by Julie-M-Zhu** [comment]
I agree with Fei, GNU seems better in popularity and clarity.
